# Simulating Coin Flips

In [3]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [17]:
# outcome of one coin flip
np.random.randint(2)

1

In [9]:
# outcomes of ten thousand coin flips
np.random.randint(2, size=10000)


array([0, 0, 0, ..., 1, 0, 1])

In [10]:
# mean outcome of ten thousand coin flips
np.random.randint(2, size=10000).mean()

0.4911

In [19]:
# outcome of one coin flip
np.random.choice([0, 1])


1

In [20]:
# outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000)

array([1, 0, 0, ..., 1, 0, 0])

In [21]:
# mean outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000).mean()

0.4994

In [22]:
# outcomes of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2])


array([0, 0, 0, ..., 0, 1, 0])

In [23]:
# mean outcome of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2]).mean()

0.1977

# Probability Quiz

In this quiz, you will simulate coin flips and die rolls to compute proportions for the following outcomes.

1.   Two fair coin flips produce exactly two heads
2.   Three fair coin flips produce exactly one head
3.   Three biased coin flips with P(H) = 0.6 produce exactly one head
4.   A die rolls an even number
5.   Two dice roll a double

Then, you'll compare these proportions with probabilities in the quizzes below.

When simulating coin flips, use 0 to represent heads and 1 to represent tails. When simulating die rolls, use the correct integers to match the numbers on the sides of a standard 6 sided die.

Also, notice that you can look at the solutions if you get stuck by clicking the orange button in the top left or check the solution link at the bottom of the page.

Use NumPy to create simulations and compute proportions for the following outcomes. The first one is done for you.

Please note again that we are using 0 to represent heads, and 1 to represent tails.

In [24]:
# import numpy
import numpy as np

## 1. Two fair coin flips produce exactly two heads

In [43]:
# simulate 1 million tests of two fair coin flips
tests = np.random.randint(2, size=(int(1e6), 2))

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly two heads
(test_sums == 0).mean()

0.249781

## 2. Three fair coin flips produce exactly one head

In [45]:
# simulate 1 million tests of three fair coin flips
tests = np.random.randint(2, size=(int(1e6),3))

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly one head
(test_sums == 2).mean()

0.374462

## 3. Three biased coin flips with P(H) = 0.6 produce exactly one head

In [46]:
# simulate 1 million tests of three biased coin flips
# hint: use np.random.choice()
tests = np.random.choice([0,1], size=(int(1e6),3), p=[0.6,0.4])

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly one head
(test_sums == 2).mean()

0.288004

## 4. A die rolls an even number

In [51]:
# simulate 1 million tests of one die roll
tests = np.random.choice(np.arange(1,7), size=(1000000))

# proportion of tests that produced an even number
(tests % 2 == 0).mean()

0.50035

## 5. Two dice roll a double

In [53]:
# simulate the first million die rolls
first = np.random.choice(np.arange(1,7), size=(1000000))

# simulate the second million die rolls
second = np.random.choice(np.arange(1,7), size=(1000000))

# proportion of tests where the 1st and 2nd die rolled the same number
(first == second).mean()

0.1665

In [54]:
import numpy as np

# Simulate 1 million tests of each outcome
tests_1 = np.random.choice([0, 1], size=(1000000, 2))
tests_2 = np.random.choice([0, 1], size=(1000000, 3))
tests_3 = np.random.choice([0, 1], size=(1000000, 3), p=[0.6, 0.4])
tests_4 = np.random.randint(1, 7, size=1000000)
tests_5 = np.random.choice(np.arange(1, 7), size=(1000000, 2))

# Calculate proportions of tests that match each outcome
prop_1 = np.mean(np.sum(tests_1, axis=1) == 0)
prop_2 = np.mean(np.sum(tests_2, axis=1) == 1)
prop_3 = np.mean(np.sum(tests_3, axis=1) == 1)
prop_4 = np.mean(tests_4 % 2 == 0)
prop_5 = np.mean(tests_5[:, 0] == tests_5[:, 1])

# Print the proportions
print("Proportion of tests that match outcome 1:", prop_1)
print("Proportion of tests that match outcome 2:", prop_2)
print("Proportion of tests that match outcome 3:", prop_3)
print("Proportion of tests that match outcome 4:", prop_4)
print("Proportion of tests that match outcome 5:", prop_5)

Proportion of tests that match outcome 1: 0.250658
Proportion of tests that match outcome 2: 0.374186
Proportion of tests that match outcome 3: 0.431758
Proportion of tests that match outcome 4: 0.500836
Proportion of tests that match outcome 5: 0.167234
